language: objective-c
osx_image: xcode8.2

before_install:
  # Use when Travis-installed ruby won't run latest cocoapods.
  # - rvm get stable --auto-dotfiles
  # - rvm install 2.2

  - gem install xcpretty

  - gem install cocoapods
  - pod --version
  - pod repo update

  - (cd Example && pod install)

  # https://github.com/travis-ci/travis-ci/issues/7031
  - echo y | fastlane snapshot reset_simulators


script:
  - set -o pipefail &&
    xcodebuild
    test
    -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2'
    -workspace Example/ObjCBSON.xcworkspace
    -scheme ObjCBSON-Example
    -sdk iphonesimulator10.2
    ONLY_ACTIVE_ARCH=NO |
    xcpretty -c

notifications:
  slack:
    secure: L60jPEUeOW1Uimwmn6SImasEaFBdsGSqoPEZsamm9poukhBL3FVqtPRmCc8WMCCTvWtr6yRS0N+CnoClPsK3nL9q/ou0jh7OFcQ5Qgkfu5DNYvnoV9/7Yy0izcj9F2ZHVjuLF/R0OXmcuxmjsh3PRMqzSH9FNe6iiSDDOSSXpCA=
