# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
before_install:
- gem install cocoapods
- (cd Example && pod install)
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/ObjCBSON-experimental.xcworkspace -scheme ObjCBSON-experimental -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
