language: objective-c
osx_image: xcode8.2

before_install:
  - test $CI && curl -sSL https://raw.githubusercontent.com/paulmelnikow/simon-says/master/simon-says -o simon-says && chmod +x simon-says
  - ./simon-says prepare
  - ./simon-says appledoc install

before_script:
  - (cd Example && pod install)
  - (cd ObjCBSONSampleApp && pod install)

script:
  - ./simon-says test Example/ObjCBSON.xcworkspace ObjCBSON-Example "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2"
  - ./simon-says test ObjCBSONSampleApp/ObjCBSONSampleApp.xcworkspace ObjCBSONSampleApp "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2"

notifications:
  slack:
    on_success: change
    secure: UI+a3Du2owOLjuWUnXV+3xN/XU5Sx1Qn2lkTz1jzexZtaYTD0kJYowBEgLMlHcXmeqVuiY1yK4F8ZFr5OkX+BpKSWIeAzCc6gO2SAHEER07XSfAKJb07+euJ2iAMqZt8prGkpBHEz2PVLFfst+xN8TCoNRUjkoFcA4oCGRZqfIo=
