language: objective-c
osx_image: xcode8.2

before_install:
  - test $CI && curl -sSL https://raw.githubusercontent.com/paulmelnikow/simon-says/master/simon-says -o simon-says && chmod +x simon-says
  - ./simon-says prepare
  - ./simon-says appledoc install

before_script:
  - (cd Example && pod install)

script:
  - ./simon-says test Example/ObjCBSON.xcworkspace ObjCBSON-Example "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2"

notifications:
  slack:
    secure: L60jPEUeOW1Uimwmn6SImasEaFBdsGSqoPEZsamm9poukhBL3FVqtPRmCc8WMCCTvWtr6yRS0N+CnoClPsK3nL9q/ou0jh7OFcQ5Qgkfu5DNYvnoV9/7Yy0izcj9F2ZHVjuLF/R0OXmcuxmjsh3PRMqzSH9FNe6iiSDDOSSXpCA=
